In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/survey/survey_dataset.csv")

In [3]:
df.head()

,Timestamp,Age Group?,Occupation?,Gender,What type of smartphone do you primarily use?,Average daily mobile screen time?,Which app categories do you use daily?,Which category do you spend the MOST time on?,How often do you see ads while using mobile apps?,Which ad formats do you encounter most frequently?,In which app category do you feel ads are MOST excessive?,Fill the following [Ads interrupt my app usage experience],Fill the following [I feel frustrated due to frequent advertisements],Fill the following [Ads reduce my enjoyment while using apps],Fill the following [Ads have caused me to close an app or stop using it temporarily],Ads have made me uninstall an app in the past,Which ad format do you tolerate the MOST?,Which time do you find ads MOST annoying?,Would you pay for an ad-free version of an app you use frequently?
0,05/02/2026 20:55:23,18–24,Student,Male,Android,4–6 hours,"Social Media, Video / OTT, Gaming, Shopping / ...","Social Media, Video / OTT, Gaming",Often,Unskippable ads,Gaming,Agree,Strongly agree,Strongly agree,Neutral,Yes,Skippable video ads,Evening,No
1,05/02/2026 20:56:07,18–24,Student,Male,iOS,4–6 hours,"Social Media, Video / OTT, Education","Social Media, Video / OTT, Education",Often,Video ads,Video / OTT,Strongly agree,Strongly agree,Agree,Agree,Yes,Skippable video ads,Evening,Yes
2,05/02/2026 20:56:19,18–24,Student,Male,iOS,More than 6 hours,"Social Media, Video / OTT, Gaming","Social Media, Video / OTT, Gaming",Sometimes,Sponsored posts,Social Media,Agree,Strongly agree,Strongly agree,Disagree,No,Skippable video ads,Evening,Yes
3,05/02/2026 20:56:51,18–24,Student,Male,Android,4–6 hours,"Social Media, Video / OTT, Shopping / E-commer...","Social Media, Shopping / E-commerce, Education",Sometimes,Video ads,Social Media,Neutral,Agree,Agree,Neutral,Yes,Rewarded ads,NaN,Yes
4,05/02/2026 20:57:04,Below 18,Student,Female,iOS,2–4 hours,"Social Media, Video / OTT, Shopping / E-commerce","Social Media, Video / OTT, Shopping / E-commerce",Sometimes,Banner ads,Video / OTT,Neutral,Neutral,Agree,Disagree,No,Banner ads,Morning,No

In [7]:
df.shape

(420, 19)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 19 columns):
 #   Column                                                                                Non-Null Count  Dtype
---  ------                                                                                --------------  -----
 0   Timestamp                                                                             420 non-null    str
 1   Age Group?                                                                            414 non-null    str
 2   Occupation?                                                                           414 non-null    str
 3   Gender                                                                                414 non-null    str
 4   What type of smartphone do you primarily use?                                         412 non-null    str
 5   Average daily mobile screen time?                                                     414 non-null    str
 6   Which app categories do you use daily?                                                395 non-null    str
 7   Which category do you spend the MOST time on?                                         389 non-null    str
 8   How often do you see ads while using mobile apps?                                     414 non-null    str
 9   Which ad formats do you encounter most frequently?                                    413 non-null    str
 10  In which app category do you feel ads are MOST excessive?                             414 non-null    str
 11  Fill the following [Ads interrupt my app usage experience]                            414 non-null    str
 12  Fill the following [I feel frustrated due to frequent advertisements]                 414 non-null    str
 13  Fill the following [Ads reduce my enjoyment while using apps]                         414 non-null    str
 14  Fill the following [Ads have caused me to close an app or stop using it temporarily]  414 non-null    str
 15  Ads have made me uninstall an app in the past                                         414 non-null    str
 16  Which ad format do you tolerate the MOST?                                             353 non-null    str
 17  Which time do you find ads MOST annoying?                                             406 non-null    str
 18  Would you pay for an ad-free version of an app you use frequently?                    414 non-null    str
dtypes: str(19)
memory usage: 160.9 KB

In [11]:
df.isnull().sum()

Timestamp                                                                                0
Age Group?                                                                               6
Occupation?                                                                              6
Gender                                                                                   6
What type of smartphone do you primarily use?                                            8
Average daily mobile screen time?                                                        6
Which app categories do you use daily?                                                  25
Which category do you spend the MOST time on?                                           31
How often do you see ads while using mobile apps?                                        6
Which ad formats do you encounter most frequently?                                       7
In which app category do you feel ads are MOST excessive?                                6
Fill the following [Ads interrupt my app usage experience]                               6
Fill the following [I feel frustrated due to frequent advertisements]                    6
Fill the following [Ads reduce my enjoyment while using apps]                            6
Fill the following [Ads have caused me to close an app or stop using it temporarily]     6
Ads have made me uninstall an app in the past                                            6
Which ad format do you tolerate the MOST?                                               67
Which time do you find ads MOST annoying?                                               14
Would you pay for an ad-free version of an app you use frequently?                       6
dtype: int64

In [13]:
df.columns = [
"timestamp",
"age_group",
"occupation",
"gender",
"smartphone_type",
"screen_time",
"daily_app_categories",
"most_used_category",
"ad_frequency",
"frequent_ad_format",
"most_excessive_ad_category",
"ads_interrupt_usage",
"ads_cause_frustration",
"ads_reduce_enjoyment",
"ads_close_app",
"ads_uninstall_app",
"tolerated_ad_format",
"most_annoying_ad_time",
"pay_for_adfree"
]

In [15]:
df.columns

Index(['timestamp', 'age_group', 'occupation', 'gender', 'smartphone_type',
       'screen_time', 'daily_app_categories', 'most_used_category',
       'ad_frequency', 'frequent_ad_format', 'most_excessive_ad_category',
       'ads_interrupt_usage', 'ads_cause_frustration', 'ads_reduce_enjoyment',
       'ads_close_app', 'ads_uninstall_app', 'tolerated_ad_format',
       'most_annoying_ad_time', 'pay_for_adfree'],
      dtype='str')

In [17]:
df = df.drop(columns=["timestamp"])

In [19]:
df.isnull().sum()

age_group                      6
occupation                     6
gender                         6
smartphone_type                8
screen_time                    6
daily_app_categories          25
most_used_category            31
ad_frequency                   6
frequent_ad_format             7
most_excessive_ad_category     6
ads_interrupt_usage            6
ads_cause_frustration          6
ads_reduce_enjoyment           6
ads_close_app                  6
ads_uninstall_app              6
tolerated_ad_format           67
most_annoying_ad_time         14
pay_for_adfree                 6
dtype: int64

In [21]:
demographic_cols = [
"age_group",
"occupation",
"gender",
"smartphone_type",
"screen_time"
]

for col in demographic_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\abish\AppData\Local\Temp\ipykernel_15260\2225661814.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].mode()[0], inplace=True)

In [23]:
usage_cols = [
"daily_app_categories",
"most_used_category"
]

for col in usage_cols:
    df[col].fillna("Unknown", inplace=True)

C:\Users\abish\AppData\Local\Temp\ipykernel_15260\2218257611.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna("Unknown", inplace=True)

In [25]:
ads_cols = [
"ad_frequency",
"frequent_ad_format",
"most_excessive_ad_category",
"ads_interrupt_usage",
"ads_cause_frustration",
"ads_reduce_enjoyment",
"ads_close_app",
"ads_uninstall_app",
"pay_for_adfree"
]

for col in ads_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\abish\AppData\Local\Temp\ipykernel_15260\397244981.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].mode()[0], inplace=True)

In [27]:
df["tolerated_ad_format"].fillna("None / Not Sure", inplace=True)

C:\Users\abish\AppData\Local\Temp\ipykernel_15260\939742511.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["tolerated_ad_format"].fillna("None / Not Sure", inplace=True)

0      Skippable video ads
1      Skippable video ads
2      Skippable video ads
3             Rewarded ads
4               Banner ads
              ...
415    Skippable video ads
416           Rewarded ads
417      Sponsored content
418           Rewarded ads
419      Sponsored content
Name: tolerated_ad_format, Length: 420, dtype: str

In [29]:
df["most_annoying_ad_time"].fillna("Unknown", inplace=True)

C:\Users\abish\AppData\Local\Temp\ipykernel_15260\4107467715.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["most_annoying_ad_time"].fillna("Unknown", inplace=True)

0        Evening
1        Evening
2        Evening
3        Unknown
4        Morning
         ...
415      Morning
416      Morning
417    Afternoon
418      Morning
419    Afternoon
Name: most_annoying_ad_time, Length: 420, dtype: str

In [31]:
df.isnull().sum()

age_group                      6
occupation                     6
gender                         6
smartphone_type                8
screen_time                    6
daily_app_categories          25
most_used_category            31
ad_frequency                   6
frequent_ad_format             7
most_excessive_ad_category     6
ads_interrupt_usage            6
ads_cause_frustration          6
ads_reduce_enjoyment           6
ads_close_app                  6
ads_uninstall_app              6
tolerated_ad_format           67
most_annoying_ad_time         14
pay_for_adfree                 6
dtype: int64

In [33]:
df.duplicated().sum()

9

In [35]:
df = df.drop_duplicates()

In [37]:
df.duplicated().sum()

0

In [39]:
df = df.convert_dtypes()

In [41]:
mapping = {
"Strongly disagree":1,
"Disagree":2,
"Neutral":3,
"Agree":4,
"Strongly agree":5
}

fatigue_cols = [
"ads_interrupt_usage",
"ads_cause_frustration",
"ads_reduce_enjoyment",
"ads_close_app"
]

for col in fatigue_cols:
    df[col+"_score"] = df[col].map(mapping)

df["ad_fatigue_index"] = df[[c+"_score" for c in fatigue_cols]].mean(axis=1)

In [43]:
df.head()

,age_group,occupation,gender,smartphone_type,screen_time,daily_app_categories,most_used_category,ad_frequency,frequent_ad_format,most_excessive_ad_category,...,ads_close_app,ads_uninstall_app,tolerated_ad_format,most_annoying_ad_time,pay_for_adfree,ads_interrupt_usage_score,ads_cause_frustration_score,ads_reduce_enjoyment_score,ads_close_app_score,ad_fatigue_index
0,18–24,Student,Male,Android,4–6 hours,"Social Media, Video / OTT, Gaming, Shopping / ...","Social Media, Video / OTT, Gaming",Often,Unskippable ads,Gaming,...,Neutral,Yes,Skippable video ads,Evening,No,4.0,5.0,5.0,3.0,4.25
1,18–24,Student,Male,iOS,4–6 hours,"Social Media, Video / OTT, Education","Social Media, Video / OTT, Education",Often,Video ads,Video / OTT,...,Agree,Yes,Skippable video ads,Evening,Yes,5.0,5.0,4.0,4.0,4.50
2,18–24,Student,Male,iOS,More than 6 hours,"Social Media, Video / OTT, Gaming","Social Media, Video / OTT, Gaming",Sometimes,Sponsored posts,Social Media,...,Disagree,No,Skippable video ads,Evening,Yes,4.0,5.0,5.0,2.0,4.00
3,18–24,Student,Male,Android,4–6 hours,"Social Media, Video / OTT, Shopping / E-commer...","Social Media, Shopping / E-commerce, Education",Sometimes,Video ads,Social Media,...,Neutral,Yes,Rewarded ads,<NA>,Yes,3.0,4.0,4.0,3.0,3.50
4,Below 18,Student,Female,iOS,2–4 hours,"Social Media, Video / OTT, Shopping / E-commerce","Social Media, Video / OTT, Shopping / E-commerce",Sometimes,Banner ads,Video / OTT,...,Disagree,No,Banner ads,Morning,No,3.0,3.0,4.0,2.0,3.00

In [45]:
df.describe(include="all")

,age_group,occupation,gender,smartphone_type,screen_time,daily_app_categories,most_used_category,ad_frequency,frequent_ad_format,most_excessive_ad_category,...,ads_close_app,ads_uninstall_app,tolerated_ad_format,most_annoying_ad_time,pay_for_adfree,ads_interrupt_usage_score,ads_cause_frustration_score,ads_reduce_enjoyment_score,ads_close_app_score,ad_fatigue_index
count,410,410,410,408,410,391,385,410,409,410,...,410,410,349,402,410,410.000000,410.000000,410.000000,410.000000,410.000000
unique,5,4,3,2,4,113,105,4,5,7,...,5,2,4,4,2,NaN,NaN,NaN,NaN,NaN
top,18–24,Student,Male,Android,4–6 hours,"Social Media, Video / OTT, Shopping / E-commerce","Social Media, Video / OTT, Gaming",Often,Video ads,Video / OTT,...,Strongly agree,No,Skippable video ads,Late night,No,NaN,NaN,NaN,NaN,NaN
freq,142,149,195,258,114,18,33,121,106,87,...,102,215,112,118,234,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.221951,3.241463,3.324390,3.243902,3.257927
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.388745,1.411700,1.396692,1.389455,0.925279
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,2.000000,2.000000,2.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.000000,3.000000,4.000000,3.000000,3.250000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.000000,4.000000,5.000000,4.000000,4.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,5.000000,5.000000,5.000000

In [47]:
df.to_csv("../data/processed/survey_cleaned.csv", index=False)

In [49]:
df.to_csv("../dashboard/dashboard_dataset_survey.csv", index=False)